<?php
require_once "database_connection.php";
$database_connection->query("SET FOREIGN_KEY_CHECKS = 0");

$database_connection->query("
CREATE TABLE IF NOT EXISTS USER_PREFERENCES (
    PREFERENCES_ID INT AUTO_INCREMENT PRIMARY KEY,
    BUDGET_LIMIT DECIMAL(10,2),
    HOUSEHOLD_SIZE INT,
    DIETARY_RESTRICTIONS TEXT,
    ALLERGIES TEXT,
    HEALTH_GOALS TEXT
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FIRST_NAME VARCHAR(50) NOT NULL,
    USER_LAST_NAME VARCHAR(50) NOT NULL,
    USER_EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE,
    USER_PHONE_NUMBER VARCHAR(10) UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    PREFERENCES_ID INT,
    USER_ROLE ENUM('USER','PROFESSIONAL','ADMIN') DEFAULT 'USER',
    SUBSCRIPTION_TYPE VARCHAR(50),
    USER_ACCOUNT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ACCOUNT_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PREFERENCES_ID) REFERENCES USER_PREFERENCES(PREFERENCES_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS RECIPE (
    RECIPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPE_NAME VARCHAR(100) NOT NULL,
    RECIPE_DESCRIPTION TEXT,
    RECIPE_INSTRUCTIONS TEXT,
    RECIPE_DIFFICULTY_LEVEL ENUM('EASY','MEDIUM','HARD') DEFAULT 'EASY',
    RECIPE_PREP_TIME_MINUTES INT DEFAULT 0,
    RECIPE_COOKING_TIME_MINUTES INT DEFAULT 0,
    CALORIES DECIMAL(10,2) DEFAULT 0,
    SERVING_SIZE INT DEFAULT 1,
    RECIPE_IMAGE VARCHAR(255),
    CATEGORY VARCHAR(50),
    INGREDIENTS TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT
);
");
$database_connection->query("
CREATE TABLE IF NOT EXISTS INGREDIENT (
    INGREDIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(100) NOT NULL,
    INGREDIENT_CATEGORY VARCHAR(50),
    UNIT_OF_MEASUREMENT VARCHAR(20),
    INGREDIENT_SHELF_LIFE_DAYS INT,
    INGREDIENT_BARCODE_SCAN VARCHAR(100),
    INGREDIENT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INGREDIENT_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS PANTRY (
    PANTRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    INGREDIENT_NAME VARCHAR(100),
    QUANTITY DECIMAL(10,2),
    PURCHASE_DATE DATE,
    EXPIRY_DATE DATE,
    BARCODE VARCHAR(100),
    LOCATION_IN_PANTRY VARCHAR(100),
    PANTRY_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PANTRY_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID)
        
)
");
$database_connection->query("
CREATE TABLE IF NOT EXISTS password_reset (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
");

$database_connection->query("SET FOREIGN_KEY_CHECKS = 1");

$database_connection->close();