<?php

require_once "database_connection.php";

$database_connection->query("SET FOREIGN_KEY_CHECKS = 0");

$database_connection->query("
CREATE TABLE IF NOT EXISTS USER_PREFERENCES (
    PREFERENCES_ID INT AUTO_INCREMENT PRIMARY KEY,
    BUDGET_LIMIT DECIMAL(10,2),
    HOUSEHOLD_SIZE INT,
    DIETARY_RESTRICTIONS TEXT,
    ALLERGIES TEXT,
    HEALTH_GOALS TEXT
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FIRST_NAME VARCHAR(50) NOT NULL,
    USER_LAST_NAME VARCHAR(50) NOT NULL,
    USER_EMAIL_ADDRESS VARCHAR(100) NOT NULL UNIQUE,
    USER_PHONE_NUMBER VARCHAR(10) UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    PREFERENCES_ID INT,
    USER_ROLE ENUM('USER','PROFESSIONAL','ADMIN') DEFAULT 'USER',
    SUBSCRIPTION_TYPE VARCHAR(50),
    USER_ACCOUNT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ACCOUNT_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PREFERENCES_ID) REFERENCES USER_PREFERENCES(PREFERENCES_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS ADMINISTRATOR (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PERMISSIONS TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS PROFESSIONAL (
    PROFESSIONAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    PROFESSIONAL_FULL_NAME VARCHAR(100) NOT NULL,
    PROFESSIONAL_EMAIL_ADDRESS VARCHAR(100),
    PROFESSIONAL_PHONE_NUMBER VARCHAR(20),
    SPECIALIZATION VARCHAR(100),
    CERTIFICATIONS TEXT,
    YEARS_OF_EXPERIENCE INT,
    BIO TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS RECIPE (
    RECIPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPE_NAME VARCHAR(100) NOT NULL,
    RECIPE_DESCRIPTION TEXT,
    RECIPE_INSTRUCTIONS TEXT,
    RECIPE_DIFFICULTY_LEVEL ENUM('EASY','MEDIUM','HARD'),
    RECIPE_PREP_TIME_MINUTES INT,
    RECIPE_COOKING_TIME_MINUTES INT,
    CALORIES DECIMAL(10,2),
    SERVING_SIZE INT
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS INGREDIENT (
    INGREDIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(100) NOT NULL,
    INGREDIENT_CATEGORY VARCHAR(50),
    UNIT_OF_MEASUREMENT VARCHAR(20),
    INGREDIENT_SHELF_LIFE_DAYS INT,
    INGREDIENT_BARCODE_SCAN VARCHAR(100),
    INGREDIENT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INGREDIENT_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS SHOP_LOCATION (
    SHOP_ID INT AUTO_INCREMENT PRIMARY KEY,
    SHOP_NAME VARCHAR(100) NOT NULL,
    SHOP_ADDRESS TEXT,
    SHOP_PHONE_NUMBER VARCHAR(20),
    SHOP_OPENING_HOURS VARCHAR(100),
    SHOP_CLOSING_HOURS VARCHAR(100)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS PANTRY (
    PANTRY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    INGREDIENT_NAME VARCHAR(100),
    QUANTITY DECIMAL(10,2),
    PURCHASE_DATE DATE,
    EXPIRY_DATE DATE,
    BARCODE VARCHAR(100),
    LOCATION_IN_PANTRY VARCHAR(100),
    PANTRY_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PANTRY_LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS MEAL_PLAN (
    MEAL_PLAN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    MEAL_PLAN_NAME VARCHAR(100) NOT NULL,
    MEAL_PLAN_DESCRIPTION TEXT,
    MEAL_PLAN_START_DATE DATE,
    MEAL_PLAN_END_DATE DATE,
    PLAN_TYPE VARCHAR(50),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS GROCERY_LIST (
    GROCERY_LIST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    GROCERY_LIST_NAME VARCHAR(100) NOT NULL,
    GROCERY_LIST_STATUS ENUM('OPEN','COMPLETED') DEFAULT 'OPEN',
    GROCERY_LIST_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GROCERY_LIST_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS GROCERY_LIST_ITEM (
    GROCERY_ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    GROCERY_LIST_ID INT NOT NULL,
    INGREDIENT_ID INT,
    INGREDIENT_NAME VARCHAR(100),
    ITEM_QUANTITY DECIMAL(10,2),
    ITEM_IS_PURCHASED BOOLEAN DEFAULT FALSE,
    ITEM_ESTIMATED_PRICE DECIMAL(10,2),
    FOREIGN KEY (GROCERY_LIST_ID) REFERENCES GROCERY_LIST(GROCERY_LIST_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS RECIPE_INGREDIENTS (
    RECIPE_INGREDIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    RECIPE_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    QUANTITY DECIMAL(10,2),
    UNIT_OF_MEASUREMENT VARCHAR(20),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS MEAL_PLAN_RECIPES (
    MEAL_PLAN_RECIPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEAL_PLAN_ID INT NOT NULL,
    RECIPE_ID INT NOT NULL,
    SCHEDULED_DATE DATE,
    MEAL_TYPE ENUM('BREAKFAST','LUNCH','DINNER','SNACK'),
    FOREIGN KEY (MEAL_PLAN_ID) REFERENCES MEAL_PLAN(MEAL_PLAN_ID),
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE(RECIPE_ID)
)
");

$database_connection->query("
CREATE TABLE IF NOT EXISTS SHOP_INVENTORY (
    SHOP_INVENTORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    SHOP_ID INT NOT NULL,
    INGREDIENT_ID INT NOT NULL,
    PRICE DECIMAL(10,2),
    AVAILABILITY ENUM('IN_STOCK','OUT_OF_STOCK') DEFAULT 'IN_STOCK',
    FOREIGN KEY (SHOP_ID) REFERENCES SHOP_LOCATION(SHOP_ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(INGREDIENT_ID)
)
");

$database_connection->query("SET FOREIGN_KEY_CHECKS = 1");

$database_connection->close();
?>
